---
abstract: 'check that a command is available'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  File::Temp: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'Minilla/v2.4.3, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-CheckBin
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Devel::CheckBin:
    file: lib/Devel/CheckBin.pm
    version: '0.04'
requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '6.52'
  parent: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/tokuhirom/Devel-CheckBin/issues
  homepage: https://github.com/tokuhirom/Devel-CheckBin
  repository: git://github.com/tokuhirom/Devel-CheckBin.git
version: '0.04'
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
  - 'Ed J <mohawk2@users.noreply.github.com>'
